FROM oven/bun:latest

WORKDIR /app

# Copy package files
COPY package.json bun.lockb ./

# Install dependencies using bun
RUN bun install

# Copy rest of the app
COPY . .

# Set environment variables
ENV PORT=3000

# Expose port
EXPOSE 3000

# Start the app
CMD ["bun", "run", "start"]