FROM oven/bun:latest

WORKDIR /app

# Copy package files
COPY package.json bun.lockb ./
RUN bun install

# Copy app files
COPY . .

# Set environment variables
ENV PORT=3000

# Expose port
EXPOSE 3000

# Start the app
CMD ["bun", "run", "start"]